lwr:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  joint0_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_0_joint
    pid: {p: 21000.0, i: 10.0, d: 0.0}
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_1_joint
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_2_joint
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_3_joint
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_4_joint
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_5_joint
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_6_joint
    pid: {p: 50000.0, i: 10.0, d: 0.0}

  # Finger 1
  j1_f1:
    type: effort_controllers/JointPositionController
    joint: f1_dof0_joint
    pid: {p: 100.0, i: 0.001, d: 1.0}
  j2_f1:
    type: effort_controllers/JointPositionController
    joint: f1_dof1_joint
    pid: {p: 10.0, i: 0.001, d: 2.0}
  j3_f1:
    type: effort_controllers/JointPositionController
    joint: f1_dof2_joint
    pid: {p: 10.0, i: 0.001, d: 2.0}
  j4_f1:
    type: effort_controllers/JointPositionController
    joint: f1_dof3_joint
    pid: {p: 10.0, i: 0.001, d: 2.0}

  # Finger 2
  j1_f2:
    type: effort_controllers/JointPositionController
    joint: f2_dof0_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j2_f2:
    type: effort_controllers/JointPositionController
    joint: f2_dof1_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j3_f2:
    type: effort_controllers/JointPositionController
    joint: f2_dof2_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j4_f2:
    type: effort_controllers/JointPositionController
    joint: f2_dof3_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}


  # Finger 3
  j1_f3:
    type: effort_controllers/JointPositionController
    joint: f3_dof0_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j2_f3:
    type: effort_controllers/JointPositionController
    joint: f3_dof1_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j3_f3:
    type: effort_controllers/JointPositionController
    joint: f3_dof2_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j4_f3:
    type: effort_controllers/JointPositionController
    joint: f3_dof3_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}

  # Thumb
  j1_th:
    type: effort_controllers/JointPositionController
    joint: thumb_dof0_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j2_th:
    type: effort_controllers/JointPositionController
    joint: thumb_dof1_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j3_th:
    type: effort_controllers/JointPositionController
    joint: thumb_dof2_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j4_th:
    type: effort_controllers/JointPositionController
    joint: thumb_dof3_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}

  # One Task Inverse Kinematics
  OneTaskInverseKinematics: 
    type: lwr_controllers/OneTaskInverseKinematics
    root_name: world
    tip_name: lwr_7_link
    pid_lwr_0_joint: {p: 250,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_1_joint: {p: 220,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_2_joint: {p: 150,  i: 6, d: 20, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_3_joint: {p: 150,  i: 5, d: 12, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_4_joint: {p: 90,  i: 5, d: 10, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_5_joint: {p: 40,  i: 5, d: 7, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_6_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}





